version: '3.8'

services:
  server:
    build: .
    command: ./scripts/start_server.sh
    volumes:
      - ./frames:/app/frames
      - ./data:/app/data
    ports:
      - "8765:8765"
    environment:
      - DISPLAY_MODE=save
      - SAVE_DIR=frames

  main:
    build: .
    command: ./scripts/start_main.sh
    volumes:
      - ./frames:/app/frames
      - ./data:/app/data
    depends_on:
      - server

  app:
    build: .
    command: ./scripts/start_app.sh
    ports:
      - "5001:5001"
    environment:
      - FLASK_APP=app.py
    volumes:
      - ./frames:/app/frames
      - ./data:/app/data
    depends_on:
      - server
      - main

volumes:
  frames:
  data: